name: Sandbox Create

on:
  pull_request:
    types:
      - opened
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  global_infra_main:
    name: "Infra (main): global"
    uses: osinfra-io/github-terraform-gcp-called-workflows/.github/workflows/gcp-plan-and-apply.yml@main
    if: ${{ github.actor != 'dependabot[bot]' }}
    with:
      checkout_ref: main
      github_environment: "Sandbox Infrastructure: Global"
      service_account: kitchen-github-actions@shared-terraform-tfbec6-sb.iam.gserviceaccount.com
      terraform_version: 1.3.6
      terraform_plan_args: -var-file=tfvars/sb.tfvars
      terraform_state_bucket: shared-terraform-tfbec6-sb-kitchen
      terraform_workspace: global-infra-sb
      working_directory: global/infra
      workload_identity_provider: projects/1089754275893/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      terraform_plan_secret_args: >-
        -var=billing_account=${{ secrets.BILLING_ACCOUNT }}

  global_infra:
    name: "Infra: global"
    uses: osinfra-io/github-terraform-gcp-called-workflows/.github/workflows/gcp-plan-and-apply.yml@main
    needs: [global_infra_main]
    with:
      checkout_ref: ${{ github.ref }}
      github_environment: "Sandbox Infrastructure: Global"
      service_account: kitchen-github-actions@shared-terraform-tfbec6-sb.iam.gserviceaccount.com
      terraform_version: 1.3.6
      terraform_plan_args: -var-file=tfvars/sb.tfvars
      terraform_state_bucket: shared-terraform-tfbec6-sb-kitchen
      terraform_workspace: global-infra-sb
      working_directory: global/infra
      workload_identity_provider: projects/1089754275893/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      terraform_plan_secret_args: >-
        -var=billing_account=${{ secrets.BILLING_ACCOUNT }}
