name: Sandbox Update

on:
  pull_request:
    types:
      - synchronize
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  global_infra:
    name: "Infra: global"
    uses: osinfra-io/github-terraform-gcp-called-workflows/.github/workflows/gcp-plan-and-apply.yml@brettcurtis/issue23
    with:
      checkout_ref: ${{ github.ref }}
      github_env: "Sandbox Infrastructure: Global"
      service_account: kitchen-github-actions@shared-terraform-tf95c8-sb.iam.gserviceaccount.com
      terraform_version: 1.3.5
      tf_plan_args: -var-file=tfvars/sb.tfvars
      tf_state_bucket: shared-terraform-tf95c8-sb-kitchen
      tf_workspace: global-infra-sb
      working_dir: global/infra
      workload_identity_provider: projects/973857465223/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      tf_plan_secret_args: >-
        -var=bridgecrew_token=${{ secrets.BRIDGECREW_API_KEY }}
